### ISSUE TITLE
Script focuses player when pressing any link on yt (Duplicate because I closed my own issue)

### ISSUE THREAD

**Issue by lihuelworks** [GregHerendi/YoutubeKeysFix#2]
I made a mistake and closed my own issue about a [problem I had with the script]( https://github.com/TheCreole/YoutubeKeysFix/issues/1#issue-664249589), focusing the player on any in-site link press of Youtube, those being:

- the "view more" buttons on comments
- the "view X replies" in comments
- adding a video to a playlist from the sidebar
- adding a video to watch later from the sidebar

I still don't know the cause of this, or if it can replicated; but if anything can be done or if there is any way I can help debugging this, please let me know.

**Comment by Calciferz** [comment]
Thank you for the report and apologies for not maintaining the project for so long.
Reopened the original issue https://github.com/Calciferz/YoutubeKeysFix/issues/1#issuecomment-1893686115, fix is there.
