### ISSUE TITLE
Can't select text on the page

### ISSUE THREAD

**Issue by Katzenwerfer** [GregHerendi/YoutubeKeysFix#4]
You cannot select any text on the page, not even text in the player itself.
It seems to me that the root of the problem is how the player is refocused when you click outside of it in the function on lines 198-205.
When commenting out the mentioned function, the problem no longer occurs, but that also breaks refocusing of the space bar into the player.

**Comment by Calciferz** [comment]
Thank you for the report @Katzenwerfer!
Indeed that was the issue.
Focusing the player was an unpractical feature anyway, so it was removed.

v1.2.0 fixes this: 7111ccfb6367e3f45f2edc8676cc0ea25c8eee6f
